/********************************************************************
* TGenDVCSDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenDVCSDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenDVCSDict();
extern void G__cpp_setup_inheritanceTGenDVCSDict();
extern void G__cpp_setup_typetableTGenDVCSDict();
extern void G__cpp_setup_memvarTGenDVCSDict();
extern void G__cpp_setup_globalTGenDVCSDict();
extern void G__cpp_setup_memfuncTGenDVCSDict();
extern void G__cpp_setup_funcTGenDVCSDict();
extern void G__set_cpp_environmentTGenDVCSDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenDVCS.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenDVCSDictLN_TClass;
extern G__linked_taginfo G__TGenDVCSDictLN_TBuffer;
extern G__linked_taginfo G__TGenDVCSDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenDVCSDictLN_TObject;
extern G__linked_taginfo G__TGenDVCSDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenDVCSDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenDVCSDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenDVCSDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenDVCSDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenDVCSDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenDVCSDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenDVCSDictLN_TGenGeo;
extern G__linked_taginfo G__TGenDVCSDictLN_TGenBase;
extern G__linked_taginfo G__TGenDVCSDictLN_TGVKelly;
extern G__linked_taginfo G__TGenDVCSDictLN_TGenDVCS;

/* STUB derived class for protected member access */
