/********************************************************************
* TGenRhoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenRhoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenRhoDict();
extern void G__cpp_setup_inheritanceTGenRhoDict();
extern void G__cpp_setup_typetableTGenRhoDict();
extern void G__cpp_setup_memvarTGenRhoDict();
extern void G__cpp_setup_globalTGenRhoDict();
extern void G__cpp_setup_memfuncTGenRhoDict();
extern void G__cpp_setup_funcTGenRhoDict();
extern void G__set_cpp_environmentTGenRhoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenRho.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenRhoDictLN_TClass;
extern G__linked_taginfo G__TGenRhoDictLN_TBuffer;
extern G__linked_taginfo G__TGenRhoDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenRhoDictLN_TObject;
extern G__linked_taginfo G__TGenRhoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenRhoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenRhoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenRhoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenRhoDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenRhoDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenRhoDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenRhoDictLN_TGenGeo;
extern G__linked_taginfo G__TGenRhoDictLN_TGenBase;
extern G__linked_taginfo G__TGenRhoDictLN_TGenRho;

/* STUB derived class for protected member access */
