/********************************************************************
* TGenPipDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenPipDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenPipDict();
extern void G__cpp_setup_inheritanceTGenPipDict();
extern void G__cpp_setup_typetableTGenPipDict();
extern void G__cpp_setup_memvarTGenPipDict();
extern void G__cpp_setup_globalTGenPipDict();
extern void G__cpp_setup_memfuncTGenPipDict();
extern void G__cpp_setup_funcTGenPipDict();
extern void G__set_cpp_environmentTGenPipDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenPip.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenPipDictLN_TClass;
extern G__linked_taginfo G__TGenPipDictLN_TBuffer;
extern G__linked_taginfo G__TGenPipDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenPipDictLN_TObject;
extern G__linked_taginfo G__TGenPipDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenPipDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenPipDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenPipDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenPipDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenPipDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenPipDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenPipDictLN_TGenGeo;
extern G__linked_taginfo G__TGenPipDictLN_TGenBase;
extern G__linked_taginfo G__TGenPipDictLN_TGenPip;

/* STUB derived class for protected member access */
