/********************************************************************
* TGenDeltPi0Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenDeltPi0Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenDeltPi0Dict();
extern void G__cpp_setup_inheritanceTGenDeltPi0Dict();
extern void G__cpp_setup_typetableTGenDeltPi0Dict();
extern void G__cpp_setup_memvarTGenDeltPi0Dict();
extern void G__cpp_setup_globalTGenDeltPi0Dict();
extern void G__cpp_setup_memfuncTGenDeltPi0Dict();
extern void G__cpp_setup_funcTGenDeltPi0Dict();
extern void G__set_cpp_environmentTGenDeltPi0Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenDeltPi0.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenDeltPi0DictLN_TClass;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TBuffer;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMemberInspector;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TObject;
extern G__linked_taginfo G__TGenDeltPi0DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TLorentzVector;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TGenGeo;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TGenBase;
extern G__linked_taginfo G__TGenDeltPi0DictLN_TGenDeltPi0;

/* STUB derived class for protected member access */
