/********************************************************************
* TGenElasDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenElasDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenElasDict();
extern void G__cpp_setup_inheritanceTGenElasDict();
extern void G__cpp_setup_typetableTGenElasDict();
extern void G__cpp_setup_memvarTGenElasDict();
extern void G__cpp_setup_globalTGenElasDict();
extern void G__cpp_setup_memfuncTGenElasDict();
extern void G__cpp_setup_funcTGenElasDict();
extern void G__set_cpp_environmentTGenElasDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenElas.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenElasDictLN_TClass;
extern G__linked_taginfo G__TGenElasDictLN_TBuffer;
extern G__linked_taginfo G__TGenElasDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenElasDictLN_TObject;
extern G__linked_taginfo G__TGenElasDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenElasDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenElasDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenElasDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenElasDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenElasDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenElasDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenElasDictLN_TGenGeo;
extern G__linked_taginfo G__TGenElasDictLN_TGenBase;
extern G__linked_taginfo G__TGenElasDictLN_TGenElas;

/* STUB derived class for protected member access */
