/********************************************************************
* TGenOmeDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenOmeDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenOmeDict();
extern void G__cpp_setup_inheritanceTGenOmeDict();
extern void G__cpp_setup_typetableTGenOmeDict();
extern void G__cpp_setup_memvarTGenOmeDict();
extern void G__cpp_setup_globalTGenOmeDict();
extern void G__cpp_setup_memfuncTGenOmeDict();
extern void G__cpp_setup_funcTGenOmeDict();
extern void G__set_cpp_environmentTGenOmeDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenOme.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenOmeDictLN_TClass;
extern G__linked_taginfo G__TGenOmeDictLN_TBuffer;
extern G__linked_taginfo G__TGenOmeDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenOmeDictLN_TObject;
extern G__linked_taginfo G__TGenOmeDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenOmeDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenOmeDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenOmeDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenOmeDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenOmeDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenOmeDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenOmeDictLN_TGenGeo;
extern G__linked_taginfo G__TGenOmeDictLN_TGenBase;
extern G__linked_taginfo G__TGenOmeDictLN_TGenOme;

/* STUB derived class for protected member access */
