/********************************************************************
* TGenDVCSCLASDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenDVCSCLASDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenDVCSCLASDict();
extern void G__cpp_setup_inheritanceTGenDVCSCLASDict();
extern void G__cpp_setup_typetableTGenDVCSCLASDict();
extern void G__cpp_setup_memvarTGenDVCSCLASDict();
extern void G__cpp_setup_globalTGenDVCSCLASDict();
extern void G__cpp_setup_memfuncTGenDVCSCLASDict();
extern void G__cpp_setup_funcTGenDVCSCLASDict();
extern void G__set_cpp_environmentTGenDVCSCLASDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenDVCSCLAS.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenDVCSCLASDictLN_TClass;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TBuffer;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TObject;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TGenGeo;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TGenBase;
extern G__linked_taginfo G__TGenDVCSCLASDictLN_TGenDVCSCLAS;

/* STUB derived class for protected member access */
